export const MODES = ['calm', 'overwhelmed', 'foggy', 'anxious', 'stressed'];

export const modeConfigs = {
  calm: {
    id: 'calm',
    name: 'Calm',
    icon: '🌿',
    tagline: 'Clear mind, full access',
    description: 'You\'re feeling steady. All content and features are fully available to you.',
    prompt: 'Everything is available. Take your time and enjoy the clarity.',
    // Tailwind utility classes (full strings so JIT includes them)
    twBg: 'bg-slate-50',
    twPanel: 'bg-white border-slate-200',
    twText: 'text-slate-900',
    twAccent: 'bg-indigo-500',
    twAccentHover: 'hover:bg-indigo-600',
    twAccentText: 'text-indigo-700',
    twAccentLight: 'bg-indigo-50',
    twBorder: 'border-slate-200',
    twCard: 'bg-white',
    twButton: 'bg-indigo-500 hover:bg-indigo-600 text-white',
    twButtonOutline: 'border-indigo-300 text-indigo-700 hover:bg-indigo-50',
    twMuted: 'text-slate-400',
    twSubtext: 'text-slate-500',
    fontSize: 'text-base',
    lineHeight: 'leading-relaxed',
    // Hex values for inline styles when needed
    hex: {
      bg: '#F8FAFC',
      accent: '#6366F1',
      accentLight: '#EEF2FF',
      text: '#0F172A',
    },
  },

  overwhelmed: {
    id: 'overwhelmed',
    name: 'Overwhelmed',
    icon: '🌸',
    tagline: 'One step at a time',
    description: 'Showing one idea at a time. You don\'t have to take it all in at once.',
    prompt: 'You\'re doing beautifully. Take it one thought at a time.',
    twBg: 'bg-violet-50',
    twPanel: 'bg-violet-100 border-violet-200',
    twText: 'text-violet-900',
    twAccent: 'bg-violet-500',
    twAccentHover: 'hover:bg-violet-600',
    twAccentText: 'text-violet-700',
    twAccentLight: 'bg-violet-100',
    twBorder: 'border-violet-200',
    twCard: 'bg-violet-50',
    twButton: 'bg-violet-500 hover:bg-violet-600 text-white',
    twButtonOutline: 'border-violet-300 text-violet-700 hover:bg-violet-50',
    twMuted: 'text-violet-300',
    twSubtext: 'text-violet-500',
    fontSize: 'text-2xl',
    lineHeight: 'leading-loose',
    hex: {
      bg: '#FAF5FF',
      accent: '#7C3AED',
      accentLight: '#EDE9FE',
      text: '#3B0764',
    },
  },

  foggy: {
    id: 'foggy',
    name: 'Foggy',
    icon: '🌥️',
    tagline: 'Structured & clear',
    description: 'Key words are highlighted. Read aloud support is available. Move at your own pace.',
    prompt: 'Take your time. You can always read it again.',
    twBg: 'bg-amber-50',
    twPanel: 'bg-amber-100 border-amber-200',
    twText: 'text-amber-900',
    twAccent: 'bg-amber-500',
    twAccentHover: 'hover:bg-amber-600',
    twAccentText: 'text-amber-800',
    twAccentLight: 'bg-amber-100',
    twBorder: 'border-amber-200',
    twCard: 'bg-amber-50',
    twButton: 'bg-amber-500 hover:bg-amber-600 text-white',
    twButtonOutline: 'border-amber-300 text-amber-800 hover:bg-amber-50',
    twMuted: 'text-amber-300',
    twSubtext: 'text-amber-600',
    fontSize: 'text-lg',
    lineHeight: 'leading-loose',
    hex: {
      bg: '#FFFBF0',
      accent: '#D97706',
      accentLight: '#FEF3C7',
      text: '#451A03',
    },
  },

  anxious: {
    id: 'anxious',
    name: 'Anxious',
    icon: '🌊',
    tagline: 'Calm & predictable',
    description: 'A quiet space. No surprises, no urgency. Everything here is safe and steady.',
    prompt: 'You are safe here. Everything is calm and predictable.',
    twBg: 'bg-teal-50',
    twPanel: 'bg-teal-100 border-teal-200',
    twText: 'text-teal-900',
    twAccent: 'bg-teal-500',
    twAccentHover: 'hover:bg-teal-600',
    twAccentText: 'text-teal-700',
    twAccentLight: 'bg-teal-100',
    twBorder: 'border-teal-200',
    twCard: 'bg-teal-50',
    twButton: 'bg-teal-500 hover:bg-teal-600 text-white',
    twButtonOutline: 'border-teal-300 text-teal-700 hover:bg-teal-50',
    twMuted: 'text-teal-300',
    twSubtext: 'text-teal-600',
    fontSize: 'text-base',
    lineHeight: 'leading-relaxed',
    hex: {
      bg: '#F0FDFA',
      accent: '#0D9488',
      accentLight: '#CCFBF1',
      text: '#042F2E',
    },
  },

  stressed: {
    id: 'stressed',
    name: 'Stressed',
    icon: '🌱',
    tagline: 'Small steps forward',
    description: 'Breaking this into small, manageable steps. You only need to do one thing at a time.',
    prompt: 'You\'re making progress. One small step at a time is still progress.',
    twBg: 'bg-green-50',
    twPanel: 'bg-green-100 border-green-200',
    twText: 'text-green-900',
    twAccent: 'bg-green-500',
    twAccentHover: 'hover:bg-green-600',
    twAccentText: 'text-green-700',
    twAccentLight: 'bg-green-100',
    twBorder: 'border-green-200',
    twCard: 'bg-green-50',
    twButton: 'bg-green-500 hover:bg-green-600 text-white',
    twButtonOutline: 'border-green-300 text-green-700 hover:bg-green-50',
    twMuted: 'text-green-300',
    twSubtext: 'text-green-600',
    fontSize: 'text-base',
    lineHeight: 'leading-relaxed',
    hex: {
      bg: '#F0FDF4',
      accent: '#16A34A',
      accentLight: '#DCFCE7',
      text: '#052E16',
    },
  },
};
